//go:build darwin

package singbox

import (
	"fmt"
	"path/filepath"
	"strings"
)

func splitDNSSetupCommands(workDir string) string {
	meta, err := loadDNSMeta(workDir)
	if err != nil {
		return ""
	}
	var builder strings.Builder
	// macOS ships mkdir/rm under /bin, but printf under /usr/bin.
	// Resolver files must be named exactly after the domain (man 5 resolver).
	builder.WriteString("/bin/mkdir -p /etc/resolver; ")
	// Drop any leftover KubeLoop resolvers (including deleted host aliases)
	// before installing the current domain set.
	builder.WriteString(kubeLoopResolverSweepCommands())
	searchLine := strings.Join(meta.Search, " ")
	for _, domain := range meta.Domains {
		path := shellQuote(filepath.Join("/etc/resolver", domain))
		content := fmt.Sprintf(
			"# Generated by KubeLoop\nnameserver %s\nport %d\nsearch %s\noptions ndots:%d\n",
			meta.Listen, meta.Port, searchLine, meta.Ndots,
		)
		fmt.Fprintf(
			&builder,
			"/usr/bin/printf '%%s' %s > %s; ",
			shellQuote(content),
			path,
		)
	}
	setupSearch := shellQuote(filepath.Join(workDir, searchSetupScriptName))
	fmt.Fprintf(&builder, "if [ -x %s ]; then /bin/sh %s; fi; ", setupSearch, setupSearch)
	return builder.String()
}

func splitDNSRestoreCommands(workDir string) string {
	var builder strings.Builder
	// Always sweep marked resolver files so host-alias domains are removed even
	// when dns-meta.json is missing or the domain list changed mid-session.
	builder.WriteString(kubeLoopResolverSweepCommands())
	if meta, err := loadDNSMeta(workDir); err == nil {
		for _, domain := range meta.Domains {
			path := shellQuote(filepath.Join("/etc/resolver", domain))
			legacy := shellQuote(filepath.Join("/etc/resolver", "kubeloop."+domain))
			fmt.Fprintf(&builder, "/bin/rm -f %s %s; ", path, legacy)
		}
	}
	restoreSearch := shellQuote(filepath.Join(workDir, searchRestoreScriptName))
	fmt.Fprintf(&builder, "if [ -x %s ]; then /bin/sh %s; fi; ", restoreSearch, restoreSearch)
	return builder.String()
}

// kubeLoopResolverSweepCommands removes every /etc/resolver file owned by KubeLoop.
// Host aliases add arbitrary domain files; sweeping by marker avoids leftovers after
// crashes or after aliases are deleted and the session reconnects.
func kubeLoopResolverSweepCommands() string {
	return "" +
		"if [ -d /etc/resolver ]; then " +
		"for f in /etc/resolver/*; do " +
		"[ -f \"$f\" ] || continue; " +
		"if /usr/bin/grep -q 'Generated by KubeLoop' \"$f\" 2>/dev/null; then /bin/rm -f \"$f\"; fi; " +
		"done; " +
		"/bin/rm -f /etc/resolver/kubeloop.*; " +
		"fi; "
}
