//go:build linux

package singbox

import (
	"fmt"
	"path/filepath"
	"strings"
)

const resolvedDropInPath = "/etc/systemd/resolved.conf.d/90-kubeloop.conf"

func splitDNSSetupCommands(workDir string) string {
	meta, err := loadDNSMeta(workDir)
	if err != nil {
		return ""
	}
	// Domains without '~' are search domains; with '~' they are routing-only.
	// Keep both so short names expand and *.cluster.local still uses our DNS.
	seen := make(map[string]struct{})
	domains := make([]string, 0, len(meta.Search)+len(meta.Domains))
	for _, domain := range meta.Search {
		if domain == "" {
			continue
		}
		if _, ok := seen[domain]; ok {
			continue
		}
		seen[domain] = struct{}{}
		domains = append(domains, domain)
	}
	for _, domain := range meta.Domains {
		if domain == "" {
			continue
		}
		routeOnly := "~" + domain
		if _, ok := seen[routeOnly]; ok {
			continue
		}
		if _, ok := seen[domain]; ok {
			// Already a search domain; systemd-resolved still routes it.
			continue
		}
		seen[routeOnly] = struct{}{}
		domains = append(domains, routeOnly)
	}
	content := fmt.Sprintf(
		"# Generated by KubeLoop\n[Resolve]\nDNS=%s:%d\nDomains=%s\n",
		meta.Listen, meta.Port, strings.Join(domains, " "),
	)
	return fmt.Sprintf(
		"/bin/mkdir -p %s; /bin/printf '%%s' %s > %s; "+
			"/usr/bin/resolvectl flush-caches >/dev/null 2>&1 || "+
			"/bin/systemctl reload-or-restart systemd-resolved >/dev/null 2>&1 || true; ",
		shellQuote(filepath.Dir(resolvedDropInPath)),
		shellQuote(content),
		shellQuote(resolvedDropInPath),
	)
}

func splitDNSRestoreCommands(string) string {
	return fmt.Sprintf(
		"if [ -f %s ] && /usr/bin/grep -q 'Generated by KubeLoop' %s 2>/dev/null; then "+
			"/bin/rm -f %s; "+
			"/usr/bin/resolvectl flush-caches >/dev/null 2>&1 || "+
			"/bin/systemctl reload-or-restart systemd-resolved >/dev/null 2>&1 || true; "+
			"fi; ",
		shellQuote(resolvedDropInPath),
		shellQuote(resolvedDropInPath),
		shellQuote(resolvedDropInPath),
	)
}
