//go:build darwin

package singbox

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSplitDNSRestoreSweepsHostAliasResolvers(t *testing.T) {
	workDir := t.TempDir()
	meta := []byte(`{
		"listen":"127.0.0.1",
		"port":1053,
		"domains":["cluster.local","app.dev"],
		"search":["default.svc.cluster.local","svc.cluster.local","cluster.local"],
		"ndots":5
	}`)
	if err := os.WriteFile(filepath.Join(workDir, "dns-meta.json"), meta, 0o600); err != nil {
		t.Fatal(err)
	}
	restore := splitDNSRestoreCommands(workDir)
	if !strings.Contains(restore, "Generated by KubeLoop") {
		t.Fatalf("restore should sweep KubeLoop-marked resolver files:\n%s", restore)
	}
	if !strings.Contains(restore, "/etc/resolver/app.dev") {
		t.Fatalf("restore should remove host alias resolver path:\n%s", restore)
	}
	setup := splitDNSSetupCommands(workDir)
	if !strings.Contains(setup, kubeLoopResolverSweepCommands()) {
		t.Fatalf("setup should sweep stale resolvers before writing:\n%s", setup)
	}
}

func TestSplitDNSRestoreWithoutMetaStillSweeps(t *testing.T) {
	restore := splitDNSRestoreCommands(t.TempDir())
	if restore == "" {
		t.Fatal("restore must not be empty when dns-meta is missing")
	}
	if !strings.Contains(restore, "Generated by KubeLoop") {
		t.Fatalf("expected marker sweep when meta missing:\n%s", restore)
	}
}
