//go:build darwin

package singbox

import (
	"fmt"
	"path/filepath"
	"strings"
)

func splitDNSSetupCommands(workDir string) string {
	meta, err := loadDNSMeta(workDir)
	if err != nil {
		return ""
	}
	var builder strings.Builder
	// macOS ships mkdir/rm under /bin, but printf under /usr/bin.
	// Resolver files must be named exactly after the domain (man 5 resolver).
	builder.WriteString("/bin/mkdir -p /etc/resolver; ")
	for _, domain := range meta.Domains {
		// Remove legacy misnamed files from earlier builds.
		legacy := shellQuote(filepath.Join("/etc/resolver", "kubeloop."+domain))
		builder.WriteString("/bin/rm -f " + legacy + "; ")

		path := shellQuote(filepath.Join("/etc/resolver", domain))
		content := fmt.Sprintf(
			"# Generated by KubeLoop\nnameserver %s\nport %d\n",
			meta.Listen, meta.Port,
		)
		fmt.Fprintf(
			&builder,
			"/usr/bin/printf '%%s' %s > %s; ",
			shellQuote(content),
			path,
		)
	}
	return builder.String()
}

func splitDNSRestoreCommands(workDir string) string {
	meta, err := loadDNSMeta(workDir)
	if err != nil {
		return ""
	}
	var builder strings.Builder
	for _, domain := range meta.Domains {
		path := shellQuote(filepath.Join("/etc/resolver", domain))
		legacy := shellQuote(filepath.Join("/etc/resolver", "kubeloop."+domain))
		fmt.Fprintf(
			&builder,
			"if /usr/bin/grep -q 'Generated by KubeLoop' %s 2>/dev/null; then /bin/rm -f %s; fi; "+
				"/bin/rm -f %s; ",
			path, path, legacy,
		)
	}
	return builder.String()
}
