//go:build darwin

package singbox

import (
	"os"
	"path/filepath"
	"strings"
)

func kubeLoopResolversPresent() bool {
	entries, err := os.ReadDir("/etc/resolver")
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "kubeloop.") {
			return true
		}
		raw, err := os.ReadFile(filepath.Join("/etc/resolver", name))
		if err != nil {
			continue
		}
		if strings.Contains(string(raw), "Generated by KubeLoop") {
			return true
		}
	}
	return false
}
