//go:build linux

package helper

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/fengqi-dev/kube-loop/internal/singbox"
)

const (
	resolvedDropIn = "/etc/systemd/resolved.conf.d/90-kubeloop.conf"
	linuxDNSMarker = "# Generated by KubeLoop"
)

func applyPlatformDNS(_ string, dns singbox.DNSMeta) error {
	seen := make(map[string]struct{})
	domains := make([]string, 0, len(dns.Search)+len(dns.Domains))
	for _, domain := range dns.Search {
		if domain != "" {
			seen[domain] = struct{}{}
			domains = append(domains, domain)
		}
	}
	for _, domain := range dns.Domains {
		routeOnly := "~" + domain
		if _, ok := seen[domain]; domain == "" || ok {
			continue
		}
		if _, ok := seen[routeOnly]; !ok {
			seen[routeOnly] = struct{}{}
			domains = append(domains, routeOnly)
		}
	}
	content := fmt.Sprintf(
		"%s\n[Resolve]\nDNS=%s:%d\nDomains=%s\nDNSSEC=no\nDNSOverTLS=no\n",
		linuxDNSMarker, dns.Listen, dns.Port, strings.Join(domains, " "),
	)
	if err := os.MkdirAll(filepath.Dir(resolvedDropIn), 0o755); err != nil {
		return err
	}
	if existing, err := os.ReadFile(resolvedDropIn); err == nil &&
		!strings.Contains(string(existing), linuxDNSMarker) {
		return fmt.Errorf("%s is not owned by KubeLoop", resolvedDropIn)
	}
	if err := os.WriteFile(resolvedDropIn, []byte(content), 0o644); err != nil {
		return err
	}
	reloadResolved()
	return nil
}

func restorePlatformDNS(_ string, _ singbox.DNSMeta) error {
	content, err := os.ReadFile(resolvedDropIn)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.Contains(string(content), linuxDNSMarker) {
		return nil
	}
	if err := os.Remove(resolvedDropIn); err != nil && !os.IsNotExist(err) {
		return err
	}
	reloadResolved()
	return nil
}

func reloadResolved() {
	// Drop-in changes require a reload; flush-caches alone does not re-read conf.d.
	_ = exec.Command("systemctl", "reload-or-restart", "systemd-resolved").Run()
	_ = exec.Command("resolvectl", "flush-caches").Run()
}

func cleanupPlatformRoutes(routes []string) {
	ip, err := exec.LookPath("ip")
	if err != nil {
		for _, candidate := range []string{"/sbin/ip", "/usr/sbin/ip"} {
			if info, statErr := os.Stat(candidate); statErr == nil && info.Mode().IsRegular() {
				ip = candidate
				break
			}
		}
	}
	if ip == "" {
		return
	}
	for _, route := range routes {
		_ = exec.Command(ip, "route", "del", route).Run()
	}
}
