// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cluster} from '../models';
import {main} from '../models';
import {update} from '../models';
import {store} from '../models';
import {helper} from '../models';
import {intercept} from '../models';
import {portfwd} from '../models';

export function AddKubeconfig():Promise<cluster.ClusterInventory>;

export function Bootstrap():Promise<main.BootstrapData>;

export function CheckForUpdates():Promise<update.Info>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GatewayInstallManifest():Promise<string>;

export function GetHostAliases(arg1:string):Promise<Array<store.HostAliasSpec>>;

export function GetManualNetwork(arg1:string):Promise<cluster.ManualNetwork>;

export function HelperStatus():Promise<helper.Status>;

export function InstallHelper():Promise<void>;

export function ListIntercepts():Promise<Array<intercept.Info>>;

export function ListMirrors():Promise<Array<intercept.Info>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<cluster.PodInfo>>;

export function ListPortForwards():Promise<Array<portfwd.Info>>;

export function ListPreviews():Promise<Array<intercept.Info>>;

export function ListServices(arg1:string,arg2:string):Promise<Array<cluster.ServiceInfo>>;

export function Namespaces(arg1:string):Promise<Array<string>>;

export function OpenUpdatePage():Promise<void>;

export function ProbeContext(arg1:string):Promise<cluster.ProbeResult>;

export function ReloadContexts():Promise<cluster.ClusterInventory>;

export function RememberSelection(arg1:string,arg2:string):Promise<void>;

export function RemoveKubeconfig(arg1:string):Promise<cluster.ClusterInventory>;

export function ResetSessions():Promise<void>;

export function SessionIntentCounts():Promise<store.SessionIntentCounts>;

export function SetHostAliases(arg1:string,arg2:Array<store.HostAliasSpec>):Promise<void>;

export function SetManualNetwork(arg1:string,arg2:cluster.ManualNetwork):Promise<void>;

export function StartIntercept(arg1:intercept.Mapping):Promise<intercept.Info>;

export function StartMirror(arg1:intercept.Mapping):Promise<intercept.Info>;

export function StartPortForward(arg1:portfwd.Request):Promise<portfwd.Info>;

export function StartPreview(arg1:intercept.PreviewRequest):Promise<intercept.Info>;

export function StopIntercept(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopPreview(arg1:string):Promise<void>;

export function UninstallHelper():Promise<void>;
