// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function Namespaces(arg1:string):Promise<Array<string>>;
